using System.Collections.Generic;
using Library;

namespace ZirconClient.Scripts;

public readonly record struct MonsterSoundSet(SoundIndex Attack, SoundIndex Struck, SoundIndex Die);

/// <summary>Mechanical port of MonsterObject.UpdateLibraries sound selection.</summary>
public static class MonsterSoundCatalog
{
    public static readonly IReadOnlyDictionary<MonsterImage, MonsterSoundSet> Entries = new Dictionary<MonsterImage, MonsterSoundSet>
    {
        [MonsterImage.Chicken] = new(SoundIndex.ChickenAttack, SoundIndex.ChickenStruck, SoundIndex.ChickenDie),
        [MonsterImage.Pig] = new(SoundIndex.PigAttack, SoundIndex.PigStruck, SoundIndex.PigDie),
        [MonsterImage.Deer] = new(SoundIndex.DeerAttack, SoundIndex.DeerStruck, SoundIndex.DeerDie),
        [MonsterImage.Cow] = new(SoundIndex.CowAttack, SoundIndex.CowStruck, SoundIndex.CowDie),
        [MonsterImage.Sheep] = new(SoundIndex.SheepAttack, SoundIndex.SheepStruck, SoundIndex.SheepDie),
        [MonsterImage.SkyStinger] = new(SoundIndex.SkyStingerAttack, SoundIndex.SkyStingerStruck, SoundIndex.SkyStingerDie),
        [MonsterImage.ClawCat] = new(SoundIndex.ClawCatAttack, SoundIndex.ClawCatStruck, SoundIndex.ClawCatDie),
        [MonsterImage.RakingCat] = new(SoundIndex.ClawCatAttack, SoundIndex.ClawCatStruck, SoundIndex.ClawCatDie),
        [MonsterImage.Wolf] = new(SoundIndex.WolfAttack, SoundIndex.WolfStruck, SoundIndex.WolfDie),
        [MonsterImage.ForestYeti] = new(SoundIndex.ForestYetiAttack, SoundIndex.ForestYetiStruck, SoundIndex.ForestYetiDie),
        [MonsterImage.CarnivorousPlant] = new(SoundIndex.CarnivorousPlantAttack, SoundIndex.CarnivorousPlantStruck, SoundIndex.CarnivorousPlantDie),
        [MonsterImage.Oma] = new(SoundIndex.OmaAttack, SoundIndex.OmaStruck, SoundIndex.OmaDie),
        [MonsterImage.OmaInfant] = new(SoundIndex.OmaAttack, SoundIndex.OmaStruck, SoundIndex.OmaDie),
        [MonsterImage.Yob] = new(SoundIndex.YobAttack, SoundIndex.YobStruck, SoundIndex.YobDie),
        [MonsterImage.TigerSnake] = new(SoundIndex.TigerSnakeAttack, SoundIndex.TigerSnakeStruck, SoundIndex.TigerSnakeDie),
        [MonsterImage.RedSnake] = new(SoundIndex.TigerSnakeAttack, SoundIndex.TigerSnakeStruck, SoundIndex.TigerSnakeDie),
        [MonsterImage.SpittingSpider] = new(SoundIndex.SpittingSpiderAttack, SoundIndex.SpittingSpiderStruck, SoundIndex.SpittingSpiderDie),
        [MonsterImage.Scarecrow] = new(SoundIndex.ScarecrowAttack, SoundIndex.ScarecrowStruck, SoundIndex.ScarecrowDie),
        [MonsterImage.OmaHero] = new(SoundIndex.OmaHeroAttack, SoundIndex.OmaHeroStruck, SoundIndex.OmaHeroDie),
        [MonsterImage.CaveBat] = new(SoundIndex.CaveBatAttack, SoundIndex.CaveBatStruck, SoundIndex.CaveBatDie),
        [MonsterImage.Scorpion] = new(SoundIndex.ScorpionAttack, SoundIndex.ScorpionStruck, SoundIndex.ScorpionDie),
        [MonsterImage.Skeleton] = new(SoundIndex.SkeletonAttack, SoundIndex.SkeletonStruck, SoundIndex.SkeletonDie),
        [MonsterImage.SkeletonAxeMan] = new(SoundIndex.SkeletonAxeManAttack, SoundIndex.SkeletonAxeManStruck, SoundIndex.SkeletonAxeManDie),
        [MonsterImage.SkeletonAxeThrower] = new(SoundIndex.SkeletonAxeThrowerAttack, SoundIndex.SkeletonAxeThrowerStruck, SoundIndex.SkeletonAxeThrowerDie),
        [MonsterImage.SkeletonWarrior] = new(SoundIndex.SkeletonWarriorAttack, SoundIndex.SkeletonWarriorStruck, SoundIndex.SkeletonWarriorDie),
        [MonsterImage.SkeletonLord] = new(SoundIndex.SkeletonLordAttack, SoundIndex.SkeletonLordStruck, SoundIndex.SkeletonLordDie),
        [MonsterImage.CaveMaggot] = new(SoundIndex.CaveMaggotAttack, SoundIndex.CaveMaggotStruck, SoundIndex.CaveMaggotDie),
        [MonsterImage.GhostSorcerer] = new(SoundIndex.GhostSorcererAttack, SoundIndex.GhostSorcererStruck, SoundIndex.GhostSorcererDie),
        [MonsterImage.GhostMage] = new(SoundIndex.GhostMageAttack, SoundIndex.GhostMageStruck, SoundIndex.GhostMageDie),
        [MonsterImage.VoraciousGhost] = new(SoundIndex.VoraciousGhostAttack, SoundIndex.VoraciousGhostStruck, SoundIndex.VoraciousGhostDie),
        [MonsterImage.DevouringGhost] = new(SoundIndex.VoraciousGhostAttack, SoundIndex.VoraciousGhostStruck, SoundIndex.VoraciousGhostDie),
        [MonsterImage.CorpseRaisingGhost] = new(SoundIndex.VoraciousGhostAttack, SoundIndex.VoraciousGhostStruck, SoundIndex.VoraciousGhostDie),
        [MonsterImage.GhoulChampion] = new(SoundIndex.GhoulChampionAttack, SoundIndex.GhoulChampionStruck, SoundIndex.GhoulChampionDie),
        [MonsterImage.ArmoredAnt] = new(SoundIndex.ArmoredAntAttack, SoundIndex.ArmoredAntStruck, SoundIndex.ArmoredAntDie),
        [MonsterImage.AntSoldier] = new(SoundIndex.ArmoredAntAttack, SoundIndex.ArmoredAntStruck, SoundIndex.ArmoredAntDie),
        [MonsterImage.AntHealer] = new(SoundIndex.ArmoredAntAttack, SoundIndex.ArmoredAntStruck, SoundIndex.ArmoredAntDie),
        [MonsterImage.AntNeedler] = new(SoundIndex.AntNeedlerAttack, SoundIndex.AntNeedlerStruck, SoundIndex.AntNeedlerDie),
        [MonsterImage.Beetle] = new(SoundIndex.KeratoidAttack, SoundIndex.KeratoidStruck, SoundIndex.KeratoidDie),
        [MonsterImage.ShellNipper] = new(SoundIndex.ShellNipperAttack, SoundIndex.ShellNipperStruck, SoundIndex.ShellNipperDie),
        [MonsterImage.VisceralWorm] = new(SoundIndex.VisceralWormAttack, SoundIndex.VisceralWormStruck, SoundIndex.VisceralWormDie),
        [MonsterImage.MutantFlea] = new(SoundIndex.MutantFleaAttack, SoundIndex.MutantFleaStruck, SoundIndex.MutantFleaDie),
        [MonsterImage.PurpleFlea] = new(SoundIndex.MutantFleaAttack, SoundIndex.MutantFleaStruck, SoundIndex.MutantFleaDie),
        [MonsterImage.BlasterMutantFlea] = new(SoundIndex.BlasterMutantFleaAttack, SoundIndex.BlasterMutantFleaStruck, SoundIndex.BlasterMutantFleaDie),
        [MonsterImage.BlueBlasterMutantFlea] = new(SoundIndex.BlasterMutantFleaAttack, SoundIndex.BlasterMutantFleaStruck, SoundIndex.BlasterMutantFleaDie),
        [MonsterImage.PoisonousMutantFlea] = new(SoundIndex.PoisonousMutantFleaAttack, SoundIndex.PoisonousMutantFleaStruck, SoundIndex.PoisonousMutantFleaDie),
        [MonsterImage.WaspHatchling] = new(SoundIndex.WasHatchlingAttack, SoundIndex.WasHatchlingStruck, SoundIndex.WasHatchlingDie),
        [MonsterImage.Centipede] = new(SoundIndex.CentipedeAttack, SoundIndex.CentipedeStruck, SoundIndex.CentipedeDie),
        [MonsterImage.ButterflyWorm] = new(SoundIndex.ButterflyWormAttack, SoundIndex.ButterflyWormStruck, SoundIndex.ButterflyWormDie),
        [MonsterImage.MutantMaggot] = new(SoundIndex.MutantMaggotAttack, SoundIndex.MutantMaggotStruck, SoundIndex.MutantMaggotDie),
        [MonsterImage.Earwig] = new(SoundIndex.EarwigAttack, SoundIndex.EarwigStruck, SoundIndex.EarwigDie),
        [MonsterImage.IronLance] = new(SoundIndex.IronLanceAttack, SoundIndex.IronLanceStruck, SoundIndex.IronLanceDie),
        [MonsterImage.LordNiJae] = new(SoundIndex.LordNiJaeAttack, SoundIndex.LordNiJaeStruck, SoundIndex.LordNiJaeDie),
        [MonsterImage.RottingGhoul] = new(SoundIndex.RottingGhoulAttack, SoundIndex.RottingGhoulStruck, SoundIndex.RottingGhoulDie),
        [MonsterImage.DecayingGhoul] = new(SoundIndex.DecayingGhoulAttack, SoundIndex.DecayingGhoulStruck, SoundIndex.DecayingGhoulDie),
        [MonsterImage.BloodThirstyGhoul] = new(SoundIndex.BloodThirstyGhoulAttack, SoundIndex.BloodThirstyGhoulStruck, SoundIndex.BloodThirstyGhoulDie),
        [MonsterImage.SpinedDarkLizard] = new(SoundIndex.SpinedDarkLizardAttack, SoundIndex.SpinedDarkLizardStruck, SoundIndex.SpinedDarkLizardDie),
        [MonsterImage.Dung] = new(SoundIndex.DungAttack, SoundIndex.DungStruck, SoundIndex.DungDie),
        [MonsterImage.UmaInfidel] = new(SoundIndex.UmaInfidelAttack, SoundIndex.UmaInfidelStruck, SoundIndex.UmaInfidelDie),
        [MonsterImage.UmaFlameThrower] = new(SoundIndex.UmaFlameThrowerAttack, SoundIndex.UmaFlameThrowerStruck, SoundIndex.UmaFlameThrowerDie),
        [MonsterImage.UmaTridentInfidel] = new(SoundIndex.UmaInfidelAttack, SoundIndex.UmaInfidelStruck, SoundIndex.UmaInfidelDie),
        [MonsterImage.UmaAnguisher] = new(SoundIndex.UmaAnguisherAttack, SoundIndex.UmaAnguisherStruck, SoundIndex.UmaAnguisherDie),
        [MonsterImage.UmaKing] = new(SoundIndex.UmaKingAttack, SoundIndex.UmaKingStruck, SoundIndex.UmaKingDie),
        [MonsterImage.SpiderBat] = new(SoundIndex.SpiderBatAttack, SoundIndex.SpiderBatStruck, SoundIndex.SpiderBatDie),
        [MonsterImage.ArachnidGazer] = new(SoundIndex.None, SoundIndex.ArachnidGazerStruck, SoundIndex.ArachnidGazerDie),
        [MonsterImage.Larva] = new(SoundIndex.LarvaAttack, SoundIndex.LarvaStruck, SoundIndex.None),
        [MonsterImage.RedMoonGuardian] = new(SoundIndex.RedMoonGuardianAttack, SoundIndex.RedMoonGuardianStruck, SoundIndex.RedMoonGuardianDie),
        [MonsterImage.RedMoonProtector] = new(SoundIndex.RedMoonProtectorAttack, SoundIndex.RedMoonProtectorStruck, SoundIndex.RedMoonProtectorDie),
        [MonsterImage.VenomousArachnid] = new(SoundIndex.VenomousArachnidAttack, SoundIndex.VenomousArachnidStruck, SoundIndex.VenomousArachnidDie),
        [MonsterImage.DarkArachnid] = new(SoundIndex.DarkArachnidAttack, SoundIndex.DarkArachnidStruck, SoundIndex.DarkArachnidDie),
        [MonsterImage.RedMoonTheFallen] = new(SoundIndex.RedMoonTheFallenAttack, SoundIndex.RedMoonTheFallenStruck, SoundIndex.RedMoonTheFallenDie),
        [MonsterImage.ViciousRat] = new(SoundIndex.ViciousRatAttack, SoundIndex.ViciousRatStruck, SoundIndex.ViciousRatDie),
        [MonsterImage.ZumaSharpShooter] = new(SoundIndex.ZumaSharpShooterAttack, SoundIndex.ZumaSharpShooterStruck, SoundIndex.ZumaSharpShooterDie),
        [MonsterImage.ZumaFanatic] = new(SoundIndex.ZumaFanaticAttack, SoundIndex.ZumaFanaticStruck, SoundIndex.ZumaFanaticDie),
        [MonsterImage.ZumaGuardian] = new(SoundIndex.ZumaGuardianAttack, SoundIndex.ZumaGuardianStruck, SoundIndex.ZumaGuardianDie),
        [MonsterImage.ZumaKing] = new(SoundIndex.ZumaKingAttack, SoundIndex.ZumaKingStruck, SoundIndex.ZumaKingDie),
        [MonsterImage.EvilFanatic] = new(SoundIndex.EvilFanaticAttack, SoundIndex.EvilFanaticStruck, SoundIndex.EvilFanaticDie),
        [MonsterImage.Monkey] = new(SoundIndex.MonkeyAttack, SoundIndex.MonkeyStruck, SoundIndex.MonkeyDie),
        [MonsterImage.EvilElephant] = new(SoundIndex.EvilElephantAttack, SoundIndex.EvilElephantStruck, SoundIndex.EvilElephantDie),
        [MonsterImage.CannibalFanatic] = new(SoundIndex.CannibalFanaticAttack, SoundIndex.CannibalFanaticStruck, SoundIndex.CannibalFanaticDie),
        [MonsterImage.SpikedBeetle] = new(SoundIndex.SpikedBeetleAttack, SoundIndex.SpikedBeetleStruck, SoundIndex.SpikedBeetleDie),
        [MonsterImage.NumaGrunt] = new(SoundIndex.NumaGruntAttack, SoundIndex.NumaGruntStruck, SoundIndex.NumaGruntDie),
        [MonsterImage.NumaWarrior] = new(SoundIndex.NumaGruntAttack, SoundIndex.NumaGruntStruck, SoundIndex.NumaGruntDie),
        [MonsterImage.NumaMage] = new(SoundIndex.NumaMageAttack, SoundIndex.NumaMageStruck, SoundIndex.NumaMageDie),
        [MonsterImage.NumaElite] = new(SoundIndex.NumaEliteAttack, SoundIndex.NumaEliteStruck, SoundIndex.NumaEliteDie),
        [MonsterImage.SandShark] = new(SoundIndex.SandSharkAttack, SoundIndex.SandSharkStruck, SoundIndex.SandSharkDie),
        [MonsterImage.StoneGolem] = new(SoundIndex.StoneGolemAttack, SoundIndex.StoneGolemStruck, SoundIndex.StoneGolemDie),
        [MonsterImage.WindfurySorceress] = new(SoundIndex.WindfurySorceressAttack, SoundIndex.WindfurySorceressStruck, SoundIndex.WindfurySorceressDie),
        [MonsterImage.CursedCactus] = new(SoundIndex.CursedCactusAttack, SoundIndex.CursedCactusStruck, SoundIndex.CursedCactusDie),
        [MonsterImage.RagingLizard] = new(SoundIndex.RagingLizardAttack, SoundIndex.RagingLizardStruck, SoundIndex.RagingLizardDie),
        [MonsterImage.SawToothLizard] = new(SoundIndex.SawToothLizardAttack, SoundIndex.SawToothLizardStruck, SoundIndex.SawToothLizardDie),
        [MonsterImage.MutantLizard] = new(SoundIndex.MutantLizardAttack, SoundIndex.MutantLizardStruck, SoundIndex.MutantLizardDie),
        [MonsterImage.VenomSpitter] = new(SoundIndex.VenomSpitterAttack, SoundIndex.VenomSpitterStruck, SoundIndex.VenomSpitterDie),
        [MonsterImage.SonicLizard] = new(SoundIndex.SonicLizardAttack, SoundIndex.SonicLizardStruck, SoundIndex.SonicLizardDie),
        [MonsterImage.GiantLizard] = new(SoundIndex.GiantLizardAttack, SoundIndex.GiantLizardStruck, SoundIndex.GiantLizardDie),
        [MonsterImage.CrazedLizard] = new(SoundIndex.CrazedLizardAttack, SoundIndex.CrazedLizardStruck, SoundIndex.CrazedLizardDie),
        [MonsterImage.TaintedTerror] = new(SoundIndex.TaintedTerrorAttack, SoundIndex.TaintedTerrorStruck, SoundIndex.TaintedTerrorDie),
        [MonsterImage.DeathLordJichon] = new(SoundIndex.DeathLordJichonAttack, SoundIndex.DeathLordJichonStruck, SoundIndex.DeathLordJichonDie),
        [MonsterImage.Minotaur] = new(SoundIndex.MinotaurAttack, SoundIndex.MinotaurStruck, SoundIndex.MinotaurDie),
        [MonsterImage.FrostMinotaur] = new(SoundIndex.FrostMinotaurAttack, SoundIndex.FrostMinotaurStruck, SoundIndex.FrostMinotaurDie),
        [MonsterImage.ShockMinotaur] = new(SoundIndex.FrostMinotaurAttack, SoundIndex.FrostMinotaurStruck, SoundIndex.FrostMinotaurDie),
        [MonsterImage.FlameMinotaur] = new(SoundIndex.FrostMinotaurAttack, SoundIndex.FrostMinotaurStruck, SoundIndex.FrostMinotaurDie),
        [MonsterImage.FuryMinotaur] = new(SoundIndex.FrostMinotaurAttack, SoundIndex.FrostMinotaurStruck, SoundIndex.FrostMinotaurDie),
        [MonsterImage.BanyaLeftGuard] = new(SoundIndex.BanyaLeftGuardAttack, SoundIndex.BanyaLeftGuardStruck, SoundIndex.BanyaLeftGuardDie),
        [MonsterImage.BanyaRightGuard] = new(SoundIndex.BanyaLeftGuardAttack, SoundIndex.BanyaLeftGuardStruck, SoundIndex.BanyaLeftGuardDie),
        [MonsterImage.EmperorSaWoo] = new(SoundIndex.EmperorSaWooAttack, SoundIndex.EmperorSaWooStruck, SoundIndex.EmperorSaWooDie),
        [MonsterImage.BoneArcher] = new(SoundIndex.BoneArcherAttack, SoundIndex.BoneArcherStruck, SoundIndex.BoneArcherDie),
        [MonsterImage.BoneBladesman] = new(SoundIndex.BoneArcherAttack, SoundIndex.BoneArcherStruck, SoundIndex.BoneArcherDie),
        [MonsterImage.BoneCaptain] = new(SoundIndex.BoneCaptainAttack, SoundIndex.BoneCaptainStruck, SoundIndex.BoneCaptainDie),
        [MonsterImage.BoneSoldier] = new(SoundIndex.BoneArcherAttack, SoundIndex.BoneArcherStruck, SoundIndex.BoneArcherDie),
        [MonsterImage.ArchLichTaedu] = new(SoundIndex.ArchLichTaeduAttack, SoundIndex.ArchLichTaeduStruck, SoundIndex.ArchLichTaeduDie),
        [MonsterImage.WedgeMothLarva] = new(SoundIndex.WedgeMothLarvaAttack, SoundIndex.WedgeMothLarvaStruck, SoundIndex.WedgeMothLarvaDie),
        [MonsterImage.LesserWedgeMoth] = new(SoundIndex.LesserWedgeMothAttack, SoundIndex.LesserWedgeMothStruck, SoundIndex.LesserWedgeMothDie),
        [MonsterImage.WedgeMoth] = new(SoundIndex.WedgeMothAttack, SoundIndex.WedgeMothStruck, SoundIndex.WedgeMothDie),
        [MonsterImage.RedBoar] = new(SoundIndex.RedBoarAttack, SoundIndex.RedBoarStruck, SoundIndex.RedBoarDie),
        [MonsterImage.ClawSerpent] = new(SoundIndex.ClawSerpentAttack, SoundIndex.ClawSerpentStruck, SoundIndex.ClawSerpentDie),
        [MonsterImage.BlackBoar] = new(SoundIndex.BlackBoarAttack, SoundIndex.BlackBoarStruck, SoundIndex.BlackBoarDie),
        [MonsterImage.TuskLord] = new(SoundIndex.TuskLordAttack, SoundIndex.TuskLordStruck, SoundIndex.TuskLordDie),
        [MonsterImage.RazorTusk] = new(SoundIndex.RazorTuskAttack, SoundIndex.RazorTuskStruck, SoundIndex.RazorTuskDie),
    };

    public static MonsterSoundSet Get(MonsterImage image) =>
        Entries.TryGetValue(image, out var sounds)
            ? sounds
            : new(SoundIndex.None, SoundIndex.GenericStruckMonster, SoundIndex.None);
}

